[package]
name = "baston-scripting"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deno_core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
dashmap = { workspace = true }
metrics = { workspace = true }
baston-protocol = { workspace = true }
bcrypt = { workspace = true }
