[package]
name = "baston-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
dashmap = { workspace = true }
tower-http = { workspace = true }
form_urlencoded = "1"
reqwest = { workspace = true }
uuid = { workspace = true }
rsa = { workspace = true }
sha1 = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
subtle = { workspace = true }
rusty_enet = { workspace = true }
rmp-serde = { workspace = true }
async-nats = { workspace = true }
bincode = { workspace = true }
futures = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
axum-server = { workspace = true }
rustls = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
baston-config = { workspace = true }
baston-protocol = { workspace = true }
baston-scripting = { workspace = true }
baston-zone = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
tempfile = "3"
toml = { workspace = true }
