[package]
name = "baston-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
baston-zonemap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
dashmap = { workspace = true }
form_urlencoded = "1"
rmp-serde = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
bitflags = { workspace = true }
bincode = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
lz4-sys = { workspace = true }
metrics = { workspace = true }

[dev-dependencies]
metrics-util = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
