//! The `db` capability (ADR-002, Tier 2): pooled database access for scripts.
//!
//! Why this is in the core rather than an addon: a resource that opens its own
//! socket and speaks SQL from a script thread produces a structurally wrong
//! result — no pooling, no backpressure, and a blocking round trip inside the
//! tick loop. That is exactly the gap `oxmysql` exists to fill in the FiveM
//! ecosystem, and it needs privileged access to the runtime to fill properly.
//!
//! What is *not* here: schemas, migrations, an ORM, query builders. Those sit
//! on the public API and belong to resources (Tier 3).
//!
//! Queries never run on a script thread. A script submits one and gets a job
//! id back immediately; the pool executes it on the tokio runtime and the
//! script collects the result later. Both engines wrap that in whatever is
//! idiomatic for them — a coroutine yield in Lua, a promise in JavaScript.

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

mod pool;
mod value;

pub use pool::{AnyPool, Driver};

/// Errors surfaced to a script.
#[derive(Debug, thiserror::Error)]
pub enum DbError {
    #[error("the db module is not configured — set [db] url in baston.toml")]
    NotConfigured,
    #[error("driver \"{0}\" is not compiled into this build")]
    DriverAbsent(String),
    #[error(
        "[db] url does not name a supported driver\n  \
         → expected one of: sqlite:…, postgres://…, mysql://…"
    )]
    UnknownUrlScheme,
    #[error("connecting to the database failed: {0}")]
    Connect(String),
    #[error("query failed: {0}")]
    Query(String),
    #[error("query exceeded its {0:?} timeout")]
    Timeout(Duration),
}

/// What a script asked the pool to do.
///
/// The four shapes cover what a game resource actually needs; anything richer
/// is a query the resource can write itself and read back as rows.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum QueryKind {
    /// Every row, as JSON objects.
    Rows,
    /// The number of affected rows.
    Execute,
    /// The first column of the first row, or null.
    Scalar,
    /// The id generated by an insert.
    Insert,
}

impl QueryKind {
    pub fn parse(name: &str) -> Option<Self> {
        match name.to_ascii_lowercase().as_str() {
            "rows" | "query" => Some(Self::Rows),
            "execute" => Some(Self::Execute),
            "scalar" => Some(Self::Scalar),
            "insert" => Some(Self::Insert),
            _ => None,
        }
    }
}

/// A submitted query, from the caller's point of view.
pub type JobId = u64;

/// The outcome of one job. `Err` carries a message a script can print.
pub type JobResult = Result<serde_json::Value, String>;

/// Handle to the database, shared by every runtime.
///
/// Cloning is cheap: it is an `Arc` over the pool and the in-flight table.
#[derive(Clone)]
pub struct Db {
    inner: Arc<DbInner>,
}

struct DbInner {
    pool: AnyPool,
    timeout: Duration,
    next_job: AtomicU64,
    /// Results waiting to be collected, keyed by job id.
    ///
    /// A `DashMap` rather than per-job channels: a script polls by id from a
    /// synchronous context, and a completed job whose script never collects it
    /// must be reclaimable — see [`Db::sweep`].
    results: dashmap::DashMap<JobId, (JobResult, Instant)>,
}

/// How long a completed-but-uncollected result is kept before it is swept.
///
/// A script that submits a query and then errors out before collecting would
/// otherwise leak one entry per query, forever.
const RESULT_RETENTION: Duration = Duration::from_secs(60);

impl Db {
    /// Connect using `config`, or fail with a message naming the fix.
    pub async fn connect(config: &baston_config::DbConfig) -> Result<Self, DbError> {
        if config.url.trim().is_empty() {
            return Err(DbError::NotConfigured);
        }
        let pool = pool::connect(&config.url, config.pool_size).await?;
        tracing::info!(
            target: "db",
            driver = %pool.driver(),
            pool_size = config.pool_size,
            "database pool ready"
        );
        Ok(Self {
            inner: Arc::new(DbInner {
                pool,
                timeout: Duration::from_secs(config.query_timeout_secs.max(1)),
                next_job: AtomicU64::new(1),
                results: dashmap::DashMap::new(),
            }),
        })
    }

    /// Build a handle over an already-connected pool (tests, and callers that
    /// own their own connection).
    pub fn from_pool(pool: AnyPool, timeout: Duration) -> Self {
        Self {
            inner: Arc::new(DbInner {
                pool,
                timeout,
                next_job: AtomicU64::new(1),
                results: dashmap::DashMap::new(),
            }),
        }
    }

    pub fn driver(&self) -> Driver {
        self.inner.pool.driver()
    }

    /// Submit a query and return immediately.
    ///
    /// The work happens on the tokio runtime, never on the caller's thread:
    /// that is the entire reason this module exists rather than a resource
    /// opening its own socket.
    pub fn submit(
        &self,
        resource: &str,
        kind: QueryKind,
        sql: String,
        params: Vec<serde_json::Value>,
    ) -> JobId {
        let id = self.inner.next_job.fetch_add(1, Ordering::Relaxed);
        let inner = Arc::clone(&self.inner);
        let resource = resource.to_owned();
        let started = Instant::now();
        tokio::spawn(async move {
            let result = match tokio::time::timeout(
                inner.timeout,
                inner.pool.run(kind, &sql, &params),
            )
            .await
            {
                Ok(Ok(value)) => Ok(value),
                Ok(Err(e)) => Err(e.to_string()),
                Err(_) => Err(DbError::Timeout(inner.timeout).to_string()),
            };
            let status = if result.is_ok() { "ok" } else { "error" };
            metrics::counter!(
                "baston_db_queries_total",
                "resource" => resource.clone(),
                "status" => status
            )
            .increment(1);
            metrics::histogram!("baston_db_query_duration_seconds")
                .record(started.elapsed().as_secs_f64());
            if let Err(message) = &result {
                tracing::warn!(target: "db", %resource, error = %message, "query failed");
            }
            inner.results.insert(id, (result, Instant::now()));
        });
        id
    }

    /// Run a query and await it here.
    ///
    /// The counterpart of [`Self::submit`], for a caller that already has an
    /// async context to await in — the JavaScript path does, and a promise is
    /// what a JS resource expects. Lua has no such context and uses
    /// submit/collect instead.
    pub async fn run(
        &self,
        resource: &str,
        kind: QueryKind,
        sql: &str,
        params: &[serde_json::Value],
    ) -> JobResult {
        let started = Instant::now();
        let result =
            match tokio::time::timeout(self.inner.timeout, self.inner.pool.run(kind, sql, params))
                .await
            {
                Ok(Ok(value)) => Ok(value),
                Ok(Err(e)) => Err(e.to_string()),
                Err(_) => Err(DbError::Timeout(self.inner.timeout).to_string()),
            };
        let status = if result.is_ok() { "ok" } else { "error" };
        metrics::counter!(
            "baston_db_queries_total",
            "resource" => resource.to_owned(),
            "status" => status
        )
        .increment(1);
        metrics::histogram!("baston_db_query_duration_seconds")
            .record(started.elapsed().as_secs_f64());
        if let Err(message) = &result {
            tracing::warn!(target: "db", %resource, error = %message, "query failed");
        }
        result
    }

    /// Collect a finished job. `None` means it is still running.
    ///
    /// One-shot: the entry is removed, so a second call for the same id reports
    /// an unknown job rather than replaying a stale result.
    pub fn collect(&self, id: JobId) -> Option<JobResult> {
        self.inner
            .results
            .remove(&id)
            .map(|(_, (result, _))| result)
    }

    /// Drop results nobody collected. Called periodically by the host.
    pub fn sweep(&self) -> usize {
        let before = self.inner.results.len();
        self.inner
            .results
            .retain(|_: &JobId, entry: &mut (JobResult, Instant)| {
                entry.1.elapsed() < RESULT_RETENTION
            });
        let dropped = before - self.inner.results.len();
        if dropped > 0 {
            tracing::debug!(target: "db", dropped, "swept uncollected query results");
        }
        dropped
    }

    /// Number of results waiting to be collected (diagnostics).
    pub fn pending_results(&self) -> usize {
        self.inner.results.len()
    }
}

impl std::fmt::Debug for Db {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Db")
            .field("driver", &self.inner.pool.driver().label())
            .field("pending_results", &self.inner.results.len())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn query_kinds_parse_from_their_script_names() {
        assert_eq!(QueryKind::parse("query"), Some(QueryKind::Rows));
        assert_eq!(QueryKind::parse("ROWS"), Some(QueryKind::Rows));
        assert_eq!(QueryKind::parse("execute"), Some(QueryKind::Execute));
        assert_eq!(QueryKind::parse("scalar"), Some(QueryKind::Scalar));
        assert_eq!(QueryKind::parse("insert"), Some(QueryKind::Insert));
        assert_eq!(QueryKind::parse("drop-everything"), None);
    }

    #[test]
    fn an_unconfigured_url_names_the_setting_to_fix() {
        let text = DbError::NotConfigured.to_string();
        assert!(text.contains("[db] url"), "{text}");
    }

    #[test]
    fn an_unknown_scheme_lists_what_is_supported() {
        let text = DbError::UnknownUrlScheme.to_string();
        for scheme in ["sqlite", "postgres", "mysql"] {
            assert!(text.contains(scheme), "{text}");
        }
    }
}
